package com.sarthak.onlineLearningPlatform.swagger;

public class SwaggerConstant {
	public static final String STATUS_CODE_200 = "200";
	public static final String FETCH_MESSAGE = "Data Fetched Successfully";	
	public static final String COURSE_RESPONSE_MESSAGE = 
			"{\r\n"
			+ "  \"status\": \"string\",\r\n"
			+ "  \"message\": \"string\",\r\n"
			+ "  \"data\": [\r\n"
			+ "    {\r\n"
			+ "      \"courseId\": 0,\r\n"
			+ "      \"title\": \"string\",\r\n"
			+ "      \"description\": \"string\",\r\n"
			+ "      \"price\": 0.0,\r\n"
			+ "      \"duration\": \"string\",\r\n"
			+ "      \"totalLectures\": 0,\r\n"
			+ "      \"assignments\": \"string\",\r\n"
			+ "      \"quizzes\": \"string\",\r\n"
			+ "      \"materials\": \"string\",\r\n"
			+ "      \"instructorId\": 0,\r\n"
			+ "      \"instructorName\": \"string\",\r\n"
			+ "      \"schoolId\": 0,\r\n"
			+ "      \"schoolName\": \"string\",\r\n"
			+ "      \"categoryId\": 0,\r\n"
			+ "      \"categoryName\": \"string\"\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";
	
	public static final String STATUS_CODE_201 = "201";
	public static final String CREATE_MESSAGE = "Data Created Successfully";	
	public static final String UPDATE_MESSAGE = "Data Updated Successfully";	
	
	public static final String CATEGORY_RESPONSE_MESSAGE = 
			"{\r\n"
			+ "  \"httpStatus\": \"string\",\r\n"
			+ "  \"message\": \"string\",\r\n"
			+ "  \"data\": [\r\n"
			+ "    {\r\n"
			+ "      \"categoryId\": 0,\r\n"
			+ "      \"categoryName\": \"string\",\r\n"
			+ "      \"description\": \"string\",\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";
	
	public static final String CATEGORY_LIST_RESPONSE_MESSAGE = 
			"{\r\n"
			+ "  \"httpStatus\": \"string\",\r\n"
			+ "  \"message\": \"string\",\r\n"
			+ "  \"data\": {\r\n"
			+ "    \"content\": [\r\n"
			+ "      {\r\n"
			+ "        \"categoryId\": 0,\r\n"
			+ "        \"categoryName\": \"string\",\r\n"
			+ "        \"description\": \"string\"\r\n"
			+ "      }\r\n"
			+ "    ],\r\n"
			+ "    \"pageable\": {\r\n"
			+ "      \"pageNumber\": 0,\r\n"
			+ "      \"pageSize\": 0,\r\n"
			+ "      \"sort\": {\r\n"
			+ "        \"empty\": true,\r\n"
			+ "        \"sorted\": true,\r\n"
			+ "        \"unsorted\": true\r\n"
			+ "      },\r\n"
			+ "      \"offset\": 0,\r\n"
			+ "      \"paged\": true,\r\n"
			+ "      \"unpaged\": true\r\n"
			+ "    },\r\n"
			+ "    \"last\": true,\r\n"
			+ "    \"totalElements\": 0,\r\n"
			+ "    \"totalPages\": 0,\r\n"
			+ "    \"size\": 0,\r\n"
			+ "    \"number\": 0,\r\n"
			+ "    \"first\": true,\r\n"
			+ "    \"numberOfElements\": 0,\r\n"
			+ "    \"sort\": {\r\n"
			+ "      \"empty\": true,\r\n"
			+ "      \"sorted\": true,\r\n"
			+ "      \"unsorted\": true\r\n"
			+ "    },\r\n"
			+ "    \"empty\": false\r\n"
			+ "  },\r\n"
			+ "  \"hasPreviousPage\": false,\r\n"
			+ "  \"hasNextPage\": false,\r\n"
			+ "  \"pageSize\": 0,\r\n"
			+ "  \"pageNumber\": 0,\r\n"
			+ "  \"totalCount\": 0\r\n"
			+ "}";
	
	public static final String INSTRUCTOR_RESPONSE_MESSAGE = 
			"{\r\n"
			+ "  \"httpStatus\": \"string\",\r\n"
			+ "  \"message\": \"string\",\r\n"
			+ "  \"data\": [\r\n"
			+ "    \"instructorId\": 0,\r\n"
			+ "    \"name\": \"string\",\r\n"
			+ "    \"email\": \"abc@example.com\",\r\n"
			+ "    \"expertise\": \"string\",\r\n"
			+ "    \"bio\": \"string\"\r\n"
			+ "  }\r\n"
			+ "}";
	
	public static final String INSTRUCTOR_LIST_RESPONSE_MESSAGE = 
			"{\r\n"
			+ "  \"httpStatus\": \"string\",\r\n"
			+ "  \"message\": \"string\",\r\n"
			+ "  \"data\": [\r\n"
			+ "  	\"content\": [\r\n"
			+ "      {\r\n"
			+ "        \"instructorId\": 0,\r\n"
			+ "        \"name\": \"string\",\r\n"
			+ "        \"email\": \"string\",\r\n"
			+ "        \"expertise\": \"string\",\r\n"
			+ "        \"bio\": \"string\"\r\n"
			+ "      }\r\n"
			+ "    ],\r\n"
			+ "    \"pageable\": {\r\n"
			+ "      \"pageNumber\": 0,\r\n"
			+ "      \"pageSize\": 0,\r\n"
			+ "      \"sort\": {\r\n"
			+ "        \"empty\": true,\r\n"
			+ "        \"unsorted\": true,\r\n"
			+ "        \"sorted\": false\r\n"
			+ "      },\r\n"
			+ "      \"offset\": 0,\r\n"
			+ "      \"unpaged\": false,\r\n"
			+ "      \"paged\": true\r\n"
			+ "    },\r\n"
			+ "    \"last\": true,\r\n"
			+ "    \"totalElements\": 0,\r\n"
			+ "    \"totalPages\": 1,\r\n"
			+ "    \"size\": 5,\r\n"
			+ "    \"number\": 0,\r\n"
			+ "    \"first\": true,\r\n"
			+ "    \"numberOfElements\": 0,\r\n"
			+ "    \"sort\": {\r\n"
			+ "      \"empty\": true,\r\n"
			+ "      \"unsorted\": true,\r\n"
			+ "      \"sorted\": false\r\n"
			+ "    },\r\n"
			+ "    \"empty\": false\r\n"
			+ "  },\r\n"
			+ "  \"hasPreviousPage\": false,\r\n"
			+ "  \"hasNextPage\": false,\r\n"
			+ "  \"pageSize\": null,\r\n"
			+ "  \"pageNumber\": null,\r\n"
			+ "  \"totalCount\": 0\r\n"
			+ "}";
	
	public static final String PROGRESS_RESPONSE_MESSAGE = 
			"{\r\n"
			+ "  \"status\": \"string\",\r\n"
			+ "  \"message\": \"string\",\r\n"
			+ "  \"data\": [\r\n"
			+ "    {\r\n"
			+ "      \"progressId\": 0,\r\n"
			+ "      \"completedLectures\": \0,\r\n"
			+ "      \"totalLectures\": \0,\r\n"
			+ "      \"percentage\": 0.0,\r\n"
			+ "      \"grade\": \"string\",\r\n"
			+ "      \"achievement\": 0,\r\n"
			+ "      \"assignments\": \"string\",\r\n"
			+ "      \"studentId\": \0,\r\n"
			+ "      \"courseId\": \0\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";
}