spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/olp
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

cloudinary:
  cloud-name:
  api-key:
  api-secret:

logging:
  file:
    name: logs/app.log
  level:
    root: INFO